/*
 * This file was generated by the Gradle 'init' task.
 */

val versionCatalog = extensions.getByType<VersionCatalogsExtension>().named("libs")

plugins {
    id("java.application.java-common-conventions")
    alias(libs.plugins.quarkus)
}

repositories {
    mavenCentral()
    mavenLocal()
}


dependencies {
    versionCatalog.findVersion("quarkusPluginVersion").ifPresent {
        implementation(enforcedPlatform("io.quarkus:quarkus-bom:${it}"))
    }

    implementation("io.quarkus:quarkus-arc")
    implementation ("org.eclipse.microprofile.rest.client:microprofile-rest-client-api:2.0")
    implementation ("com.fasterxml.jackson.core:jackson-databind")
    implementation ("io.quarkus:quarkus-resteasy-reactive-jackson")
    implementation ("io.quarkus:quarkus-resteasy-reactive-jsonb")
    implementation ("io.quarkus:quarkus-smallrye-jwt")
    implementation ("io.quarkus:quarkus-oidc")
    implementation ("io.quarkus:quarkus-undertow")


}

group = "com.mhp"
version = "1.0.0-SNAPSHOT"


