/*
 * This file was generated by the Gradle 'init' task.
 */



plugins {
    id("java.application.java-application-conventions")
}

repositories {
    mavenCentral()
    mavenLocal()
}



dependencies {

}

group = "com.mhp"
version = "1.0.0-SNAPSHOT"


