
-- Add foreign key constraint for WorkspaceBooking
ALTER TABLE WORKSPACE_BOOKINGS
ADD CONSTRAINT FK_WORKSPACE_ID FOREIGN KEY (workspace_id) REFERENCES WORKSPACE(id),
ADD CONSTRAINT FK_USER_WORKSPACE_BOOKING FOREIGN KEY (user_id) REFERENCES APP_USER(id);

