
-- Add foreign key constraint for SeatBooking

ALTER TABLE OFFICE_DESK_BOOKINGS
ADD CONSTRAINT FK_OFFICE_DESK_BOOKING_OFFICE_DESK
FOREIGN KEY (desk_id) REFERENCES OFFICE_DESK(id),
ADD CONSTRAINT FK_OFFICE_DESK_BOOKING_USER
FOREIGN KEY (user_id) REFERENCES APP_USERS(id);

-- Add foreign key constraint for MeetingBooking
ALTER TABLE MEETING_ROOM_BOOKINGS
ADD CONSTRAINT FK_MEETING_ROOM FOREIGN KEY (meeting_room_id) REFERENCES MEETING_ROOM(id),
ADD CONSTRAINT FK_USER_MEETING_ROOM_BOOKING FOREIGN KEY (user_id) REFERENCES APP_USER(id);

