[versions]
lombok-version = "1.18.30"
junit-version= "5.9.3"
hibernate-orm-version="6.3.1.Final"
flyway-core-version="10.4.1"
flyway-database-postgresql-version="10.4.1"
quarkusPluginVersion="3.7.3"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok-version" }
junit= { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-version" }
flyway-core= { module = "org.flywaydb:flyway-core", version.ref = "flyway-core-version" }
flyway-database-postgresql= { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway-database-postgresql-version" }


[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkusPluginVersion" }
hibernate-orm = { id = "org.hibernate", version.ref = "hibernate-orm-version" }
