/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mhp.app;

import java.application.list.LinkedList;

import static java.application.utilities.StringUtils.join;
import static java.application.utilities.StringUtils.split;
import static com.mhp.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
