/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mhp.app;


import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


import org.springframework.context.ApplicationContext;

@SpringBootApplication
public class App {
    @Value("${DB_URL}")
    private String dbUrl;

    @Value("${DB_USER}")
    private String dbUser;

    @Value("${DB_PASSWORD}")
    private String dbPassword;

    public static void main(String[] args) {
        ApplicationContext context = SpringApplication.run(App.class, args);

        App application = context.getBean(App.class);
        application.logProperties();
    }

    private void logProperties() {
        System.out.println("DB URL: " + dbUrl);
        System.out.println("DB User: " + dbUser);
        System.out.println("DB Password: " + dbPassword);
    }
}


