/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mhp.app;

import jakarta.enterprise.context.ApplicationScoped;

@ApplicationScoped
class MessageUtils {
    public static String getMessage() {
        return "Hello World!";
    }
}
