/*
 * This file was generated by the Gradle 'init' task.
 */

val versionCatalog=extensions.getByType<VersionCatalogsExtension>().named("projectLibs")

plugins {
    // Apply the java Plugin to add support for Java.
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    versionCatalog.findLibrary("lombok").ifPresent {
        implementation(it)
        annotationProcessor(it)

    }

    versionCatalog.findLibrary("junit").ifPresent{
        testImplementation(it)
        testRuntimeOnly(it)
    }
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")


}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
